name: Nix Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule: # execute every week
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.8.0

      - name: Check Flake
        run: nix flake check --all-systems

  create-pr:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() && needs.build.result == 'failure' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.8.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Rebuild with Python
        run: |
          nix-shell -p "python3.withPackages (ps: with ps; [ requests ])" --run "python update.py"

      - name: Create Pull Request
        if: 
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          add-paths: universities.nix
          delete-branch: true
          commit-message: "fix: update hashes"
          title: Updated hashes in universities.nix
          body: |
            Automatic pull request generated with `update.py`.
          labels: |
            bug
          assignees: MayNiklas
          reviewers: MayNiklas
          draft: false
